p1: 1.1.cpp
	g++ -Wall -o p1 1.1.cpp

p2: testStack.cpp
	g++ -Wall -o p2 testStack.cpp

p3: testLinkedList.cpp
	g++ -Wall -o p3 testLinkedList.cpp

p4: 1.4.cpp
	g++ -Wall -o p4 1.4.cpp

p5: 1.5.cpp
	g++ -Wall -o p5 1.5.cpp

all: p1 p2 p3 p4 p5

clean:
	rm p1 p2 p3 p4 p5