p1: Bucket.cpp
	g++ -Wall -o p1 Bucket.cpp

p2: Counting.cpp
	g++ -Wall -o p2 Counting.cpp

p3: Words.cpp
	g++ -Wall -o p3 Words.cpp

p4: Radix.cpp
	g++ -Wall -o p4 Radix.cpp
	
all: p1 p2 p3 p4
	./p1
	./p2
	./p3
	./p4

clean:
	rm p1 p2 p3 p4